<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.apeloa</groupId>
        <artifactId>apeloa-agent-java</artifactId>
        <version>0.1.0-SNAPSHOT</version>
    </parent>

    <artifactId>agent-admin</artifactId>
    <name>apeloa-agent :: agent-admin</name>
    <description>模型指标采样、审计、RBAC/配额</description>

    <dependencies>
        <dependency>
            <groupId>com.apeloa</groupId>
            <artifactId>agent-core</artifactId>
        </dependency>
    </dependencies>
</project>
